CREATE OR REPLACE TRIGGER "STAGING_CRIME_TRIGGER"
    BEFORE INSERT ON STAGING_CRIME_DATA
    FOR EACH ROW
BEGIN
    :NEW.STAGING_CRIME_ID := STAGING_CRIME_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER "GB_ID_TRIGGER"
    BEFORE INSERT ON GOOD_BAD_DATA
    FOR EACH ROW
BEGIN
    :NEW.GB_ID := GB_ID_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRANSFORM_LOCATION_TRIGGER
    BEFORE INSERT ON TRANSFORM_LOCATION
    FOR EACH ROW
BEGIN
    :NEW.region_key := TRANSFORM_LOCATION_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRANSFORM_TIME_TRIGGER
    BEFORE INSERT ON TRANSFORM_TIME
    FOR EACH ROW
BEGIN
    :NEW.date_id := TRANSFORM_TIME_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRANSFORM_CRIME_TYPE_TRIGGER
    BEFORE INSERT ON TRANSFORM_CRIME_TYPE
    FOR EACH ROW
BEGIN
    :NEW.crime_type_key := TRANSFORM_CRIME_TYPE_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRANSFORM_POLICE_STATION_TRIGGER
    BEFORE INSERT ON TRANSFORM_POLICE_STATION
    FOR EACH ROW
BEGIN
    :NEW.station_key := TRANSFORM_POLICE_STATION_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRANSFORM_CRIME_STATUS_TRIGGER
    BEFORE INSERT ON TRANSFORM_CRIME_STATUS
    FOR EACH ROW
BEGIN
    :NEW.crime_status_key := TRANSFORM_CRIME_STATUS_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER DIM_LOCATION_TRIGGER
    BEFORE INSERT ON DIM_LOCATION
    FOR EACH ROW
BEGIN
    :NEW.region_key := DIM_LOCATION_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER DIM_TIME_TRIGGER
    BEFORE INSERT ON DIM_TIME
    FOR EACH ROW
BEGIN
    :NEW.time_key := DIM_TIME_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER DIM_CRIME_STATUS_TRIGGER
    BEFORE INSERT ON DIM_CRIME_STATUS

    FOR EACH ROW
BEGIN
    :NEW.CRIME_STATUS_KEY := DIM_CRIME_STATUS_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER DIM_CRIME_TYPE_TRIGGER
    BEFORE INSERT ON DIM_CRIME_TYPE
    FOR EACH ROW
BEGIN
    :NEW.crime_type_key := DIM_CRIME_TYPE_SEQ.NEXTVAL; 
END;

CREATE OR REPLACE TRIGGER DIM_POLICE_STATION_TRIGGER
    BEFORE INSERT ON DIM_POLICE_STATION
    FOR EACH ROW
BEGIN
    :NEW.police_station_key := DIM_POLICE_STATION_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER FACT_CRIME_TRIGGER
    BEFORE INSERT ON FACT_CRIME
    FOR EACH ROW
BEGIN
    :NEW.FACT_CRIME_KEY := FACT_CRIME_SEQ.NEXTVAL;
END;